name: "Claim an Issue"

on: [issue_comment]

jobs:
  claim:
    runs-on: ubuntu-latest
    steps:
    - uses: bhermann/issue-volunteer@v0.1.12
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
